[package]
name = "redis_aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
redis = { version = "0.23", features = ["tokio-comp"] }
tokio-stream = "0.1"
log = "0.4"
env_logger = "0.10"